name: tlrdr-nx

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [$default-branch]

jobs:
  switch-standalone:
    name: Switch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          docker run -e ENABLE_COMPATIBILITY_REPORTING -v $GITHUB_WORKSPACE:/build_dir devkitpro/devkita64 /bin/bash -ex /build_dir/.github/workflows/buildSwitch.sh
      - uses: actions/upload-artifact@v3
        with:
          name: Nintendo Switch
          path: |
            *.ovl
